version: "3.9"
services:
    postgres:
      image: postgres:15
      container_name: postgres_container
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
        POSTGRES_DB: billingsys
      ports:
        - "5432:5432"
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U postgres" ]
        interval: 10s
        timeout: 5s
        retries: 5

    app:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: go_app_container
      environment:
        DB_HOST: postgres
        DB_PORT: 5432
        DB_USER: postgres
        DB_PASSWORD: password
        DB_NAME: billingsys
      ports:
        - "8000:8000"
      depends_on:
        postgres:
          condition: service_healthy


    prometheus:
      image: prom/prometheus
      container_name: prometheus
      volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml
      ports:
        - "9090:9090"
      networks:
        - app_network

    grafana:
      image: grafana/grafana
      container_name: grafana
      ports:
        - "3000:3000"
      environment:
        - GF_SECURITY_ADMIN_USER=admin
        - GF_SECURITY_ADMIN_PASSWORD=admin
      networks:
        - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge